# ===============================
# APP
# ===============================
spring.application.name=smart-health-backend
server.port=${PORT:8080}

# ===============================
# DATABASE (ENV BASED - IMPORTANT)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true

spring.datasource.username=postgres.dptdbduujonhzrneomew
spring.datasource.password=Santosh5782@@

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# LOG
# ===============================
logging.level.org.springframework.web=INFO
logging.level.com.smarthealth=DEBUG
logging.level.org.hibernate.SQL=DEBUG
